Scale:
  enabled: true
  plot: false
  output: "outScale.csv"
  Location: "$GOPATH/src/dispatchframework/benchmark/pkg/benchmarkscale"
  Samples: 2
Timing:
  enabled: false
  plot: false
  output: "outTime.csv"
  Location: "$GOPATH/src/dispatchframework/benchmark/pkg/benchmarktiming"
  samples: 2
Api:
  enabled: false
  plot: false
  output: "outApi.csv"
  Location: "$GOPATH/src/dispatchframework/benchmark/pkg/benchmarkapi"
  Samples: 2
