---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/starkandwayne/concourse-tutorial.git
    branch: develop
- name: benchmark-master
  type: git
  source:
    uri: https://github.com/dispatchframework/benchmark.git
    branch: nkaashoek-updateci
    
jobs:
- name: benchmarker
  public: true
  plan:
  - get: benchmark
    resource: benchmark-master
  - get: resource-tutorial
  - task: hello-world
    file: resource-tutorial/tutorials/basic/task-hello-world/task_hello_world.yml
  - task: build-benchmark
    file: benchmark/ci/make-benchmark.yml
